### ISSUE TITLE
Always specify explicitly that methods do not change an object in place but return a new one

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#189]
Users that are coming from other libraries like `scikit-learn` could easily forget that methods like `fit` do not work in place but return a new, fitted model/transformer.

We should always highlight this in the docstrings of these methods. This includes
* `fit` methods of `TableTransformer`s
* `fit` methods of `Classifier`s
* `fit` methods of `Regressor`s
* methods of `Table` that return a `Table`.

See https://stdlib.safe-ds.com/en/latest/development/guidelines/#document-api-elements for the required docstring format.

**Comment by zzril** [comment]
Some of the methods of `Table` that return a `Table` do actually modify the original table in-place. E.g. `remove_columns()`, which internally uses Pandas' `drop` method.
Is this intentional? If so, this issue needs further clarification on which methods' documentation needs to be updated.
If not, these methods need to be changed in order to actually return copies.

**Comment by lars-reimann** [comment]
As discussed, the `pandas` methods don't change data frames in place unless the `in_place` paramater is set to `True`.
