### ISSUE TITLE
Pytest can't detect 2 or more outliers in a function

### ISSUE THREAD

**Issue by jxnior01** [Safe-DS/Stdlib#274]
### Describe the bug

The following function: _**def remove_rows_with_outliers**_ doesn't perform its function correctly because **it can only detect and remove a maximum of 1 outlier**. That is, 2 or more outliers should be removed but that doesn't work.

### To Reproduce

1.  Run the following function: **_test_should_remove_rows_with_outliers_** in _/Stdlib/tests/safeds/data/tabular/containers/table/test_remove_rows_with_outliers.py_ 

> The Tests should run successfully and remove only 1 row containing an outlier

2.  Add 1 or more outliers to an existing column e.g _col1, col2 or col3._ 

> Outlier Definition:  An outlier is defined as a value that has a distance of more than 3 standard deviations from the column mean.  Missing values are not considered outliers. They are also ignored during the calculation of the standard deviation.

3. Repeat step 1

### Expected behavior

_All Outliers should be detected and removed._

**Comment by zzril** [comment]
The test function should be named "test_should_remove_rows_with_outliers", right?

**Comment by Marsmaennchen221** [comment]
The current function can remove mutliple outliers. It is possible that you added another high value but with this addition the outliers were no outliers anymore because of the small data you used to test this. In #309 I added 2 new tests that test mutliple outliers in different columns and multiple outliers in the same column.
