### ISSUE TITLE
refactor: Introduce Abstract Base Class `Model` and add `fit` and `predict` methods to `Table`

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#352]
### Is your feature request related to a problem?

* Inconsistency: For `Transformer`s, we have both a `transform` method in the `Transformer` class as well as a `transform_table` in the `Table` class. For the (models' and transformers') `fit` methods, there is no such method inside the `Table` class.
* `Classifier`s and `Regressor`s share API design and conceptual functionality, but there is no suitable common super type that allows for uniform handling.

### Desired solution

Introduce new class `Model` as parent class for `Classifier` and `Regressor`.

Introduce methods:
* `fit_model(Model)` to `Table` class
* `fit_transformer(Transformer)` to `Table` class
* `predict(Model)` to `Table` class
(Analogous to `transform_table` method in `Table` class.)

Override these appropriately in `TaggedTable` (see #58).

**Comment by lars-reimann** [comment]
So far, this superclass is something I've deliberately avoided since I don't see much use in it.

* There are different types of ML models, which require different training data. Classifiers and regressors are both supervised models, requiring labeled data (`TaggedTable`). Unsupervised models, for example, could work with a normal `Table`. Therefore, at best we could create a `SupervisedModel` class and make `Classifier` and `Regressor` subclasses of that.
* Even then, we usually need to know whether we are dealing with a classifier or regressor, or we wouldn't be able to use any metrics.
* Because of this, we would also need multiple methods on `Table` or its subclasses (e.g. `fit_supervised_model` on `TaggedTable` or `fit_unsupervised_model` on `Table`).
* Unsupervised models also don't make predictions, so we also can't just add a `predict` method to `Table` but need multiple.
* We might also want to train / make predictions with supervised models on other types of data like images, so those also need additional methods.

Overall, I think this proposal pollutes the data containers too much. Moreover, it introduces a cyclic dependency between the `data` package and the `ml` package, which can lead to numerous problems in Python. At the moment we only have a dependency from `ml` to `data`, which also matches the conceptual model I have of the domain (you need data to do ML but don't need ML to work with data).

Because of this, I'd strongly vote against
* `Model` class
* `fit_model` method
* `predict` method

I also don't like `fit_transformer` on `Table` since it works mostly on the `Transformer` rather than the `Table` and, thus, belongs to the `Transformer` class. This is opposes to `transform_table`, which mostly works on the `Table`, so it makes sense to have it in the `Table` class. The `transform` methods on `Transformer` are just necessary to have different transformation methods (Strategy design pattern).

**This leaves a potential `SupervisedModel` ABC, with `Classifier` and `Regressor` as subclasses.** But I'd only add that once we have a use case for it.

**Comment by lars-reimann** [comment]
Superseded by #377.
